server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tw_mall_user?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
zuul:
  routes:
    product:
      url: http://localhost:8081/products
      path: /products/**
    order:
      url: http://localhost:8082/orders
      path: /orders/**
management:
  endpoints:
    web:
      exposure:
        include: routes,filters


